src/django_taggsonomy/urls.py
# -*- coding: utf-8 -*-
"""
Taggsonomy URL Configuration
"""

from django.urls import path

from .views import (add_tags, remove_tag, remove_subtag, remove_supertag,
                    unexclude_tag, TagCreateView, TagDeleteView, TagEditView,
                    TagListView)

app_name = 'taggsonomy'

urlpatterns = [
    path('', TagListView.as_view(), name='tag-list'),
    path('create', TagCreateView.as_view(), name='create-tag'),
    path('<int:pk>', TagEditView.as_view(), name='edit-tag'),
    path('<int:pk>/delete', TagDeleteView.as_view(), name='delete-tag'),
    path('<int:tag_id>/remove_subtag/<int:subtag_id>',
         remove_subtag, name='remove-subtag'),
    path('<int:tag_id>/remove_supertag/<int:supertag_id>',
         remove_supertag, name='remove-supertag'),
    path('<int:tag_id>/unexclude/<int:excluded_tag_id>',
         unexclude_tag, name='unexclude-tag'),
    path('<int:tagset_id>/add', add_tags, name='add-tags'),
    path('<int:tagset_id>/remove/<int:tag_id>', remove_tag, name='remove-tag'),
]

src/django_taggsonomy/models/tags.py
# -*- coding: utf-8 -*-
from colorinput.models import ColorField
from django.db import models
from django.urls import reverse

from ..errors import (CircularInclusionError, CommonSubtagExclusionError,
                     MutualExclusionError, MutuallyExclusiveSupertagsError,
                     NoSuchTagError, SelfExclusionError,
                     SimultaneousInclusionExclusionError,
                     SupertagAdditionWouldRemoveExcludedError)
from .base import ExclusionTagSet, SubTagSet, SuperTagSet


def check_common_subtags(*tags):
    """
    Check whether the given tags have at least one common subtag.

    returns True if that is the case, False otherwise
    """
    subtag_sets = set([tag.get_all_subtags() for tag in tags])
    return Tag.objects.intersection(*subtag_sets).exists()


def check_mutually_exclusive_tags(tags):
    """
    Check whether the given set of tags contains mutually exclusive tags.

    returns True if that is the case, False otherwise
    """
    found_exclusion = False
    for tag in tags:
        for other_tag in tags - set([tag]):
            if tag.excludes(other_tag):
                found_exclusion = True
                break
    return found_exclusion


class TagManager(models.Manager):

    def get_by_name(self, name):
        """
        Return the Tag with the given name

        raises NoSuchTagError, if no tag by that name exists
        """
        try:
            return self.get(name=name)
        except Tag.DoesNotExist:
            raise NoSuchTagError

    def get_or_create_by_name(self, name):
        """
        Return a Tag with the given name

        creates a Tag, if no tag by that name exists
        """
        tag, _ = self.get_or_create(name=name)
        return tag

    def get_tag_from_argument(self, argument, create_nonexisting=False):
        """
        Return a Tag object from the positional argument, which may be:
        - a tag instances (Tag object),
        - a tag name (Tag.name (str)),
        - or a tag ID (Tag.pk (int)).

        If the argument is a str and no tag by that name exists:
        - raise NoSuchTagError, if create_nonexisting is False
        - create and return such a Tag otherwise.

        raises NoSuchTagError if the argument is an int and no tag with
        such an ID exists.
        """
        if isinstance(argument, Tag):
            # It's already a Tag object, let's just use it.
            return argument
        elif isinstance(argument, str):
            # It's a string, i.e. it should be a tag name...
            if create_nonexisting:
                return self.get_or_create_by_name(argument)
            else:
                return self.get_by_name(argument)
        elif isinstance(argument, int):
            # It's an integer, i.e. it should be the tag's ID.
            try:
                return self.get(pk=argument)
            except Tag.DoesNotExist:
                raise NoSuchTagError
        else:
            # Unsupported type
            raise NoSuchTagError

    def get_tags_from_arguments(self, *args, create_nonexisting=False):
        """
        Return a set of Tag objects from positional arguments, which may be:
        - tag instances (Tag objects),
        - tag names (Tag.name (str)),
        - or tag IDs (Tag.pk (int)).
        """
        # Also validate tags individually.
        # Collect errors before raising or raise at the first problem
        # encountered? Currently raises at first error...
        tags = set()
        for argument in args:
            tags.add(
                self.get_tag_from_argument(
                    argument,
                    create_nonexisting=create_nonexisting)
            )
        return tags


class Tag(models.Model):
    _inclusions = models.ManyToManyField('self', symmetrical=False)
    _exclusions = models.ManyToManyField('self')
    name = models.CharField(max_length=256, unique=True)
    color = ColorField(default="d0d0d0")
    objects = TagManager()

    def __str__(self):
        return self.name

    def add_supertags_to_tagset(self, tagset):
        """
        Add this tags supertags (and their supertags etc. ad finitum)
        to the given tagset
        """
        supertags = Tag.objects.filter(_inclusions=self)
        tagset.add(*supertags)
        for supertag in supertags:
            supertag.add_supertags_to_tagset(tagset)

    def add_tag_to_subtagsets(self, tag):
        """
        Add the given tag (instance, id or name) to any tagset
        containing any subtag of this tag.
        """
        for subtag in self._inclusions.all():
            subtag.add_tag_to_tagsets(tag)
            subtag.add_tag_to_subtagsets(tag)

    def add_tag_to_tagsets(self, tag):
        """
        Add the given tag (instance, id or name) to any tagset already
        containing this tag.
        """
        tag_instance = Tag.objects.get_tag_from_argument(tag)
        from .tagsets import TagSet
        for tagset in TagSet.objects.filter(_tags__id=self.id):
            tagset.add(tag_instance)

    def exclude(self, tag):
        """
        Add the given tag (instance, id or name) to this tag's exclusion set
        and vice versa.

        Tags that exclude each other will never be present in the same tag set.

        A tag may not exclude itself, as that makes no logical sense.
        Attempts to do so will raise a SelfExclusionError.

        A tag may not exclude another tag if both are already jointly present in
        the same TagSet.
        Attempts to do this will raise a MutualExclusionError.

        A tag that includes another tag, or is included by it, even indirectly,
        may not simultaneously exclude said other tag.
        Attempts to do this will raise a SimultaneousInclusionExclusionError.

        A tag may also not exclude another tag if they share common subtag, as
        this would create a situation where a tag could have mutually exclusive
        supertags. Attempts to do this will raise a CommonSubtagExclusionError.
        """
        tag_instance = Tag.objects.get_tag_from_argument(tag)
        if tag_instance == self:
            raise SelfExclusionError
        elif self.includes(tag_instance) or tag_instance.includes(self):
            raise SimultaneousInclusionExclusionError
        elif check_common_subtags(self, tag_instance):
            raise CommonSubtagExclusionError
        elif any([tag_instance in tagset for tagset in self.tagsets.all()]):
            raise MutualExclusionError
        else:
            self._exclusions.add(tag_instance)

    def excludes(self, tag):
        """
        Return True if this tag excludes the given tag (instance, id or name),
        otherwise False.
        """
        tag_instance = Tag.objects.get_tag_from_argument(tag)
        return self._exclusions.filter(id=tag_instance.id).exists()

    @property
    def exclusions(self):
        return ExclusionTagSet(self)

    def get_absolute_url(self):
        return reverse('taggsonomy:edit-tag', args=(self.id,))

    def get_all_subtags(self):
        """
        Return a TagQuerySet of this tag's subtags
        and their subtags etc. ad finitum
        """
        direct_subtags = self.get_direct_subtags()
        all_subtags = Tag.objects.none().union(direct_subtags)
        for tag in direct_subtags.all():
            all_subtags = all_subtags.union(tag.get_all_subtags())
        return all_subtags

    def get_all_supertags(self):
        """
        Return a TagQuerySet of this tag's supertags
        and their supertags etc. ad finitum
        """
        direct_supertags = self.get_direct_supertags()
        all_supertags = Tag.objects.none().union(direct_supertags)
        for tag in direct_supertags.all():
            all_supertags = all_supertags.union(tag.get_all_supertags())
        return all_supertags

    def get_direct_subtags(self):
        """
        Return a TagQuerySet of this tag's *direct* subtags,
        i.e. other tags directly included by this one.
        """
        return self._inclusions.all()
        
    def get_direct_supertags(self):
        """
        Return a TagQuerySet of this tag's *direct* supertags,
        i.e. other tags directly including this one.
        """
        return Tag.objects.filter(_inclusions=self)

    def get_excluded_tags(self):
        """
        Return a TagQuerySet of this tag's excluded tags,
        i.e. other tags excluded by (and hence, excluding) this one.
        """
        return self._exclusions.all()

    def get_indirect_subtags(self):
        """
        Return a TagQuerySet of this tag's *indirect* subtags,
        i.e. subtags of this tag's direct subtags, but excluding the direct
        subtags themselves.
        """
        direct_subtags = self.get_direct_subtags()
        all_subtags = self.get_all_subtags()
        return all_subtags.difference(direct_subtags)

    def get_indirect_supertags(self):
        """
        Return a TagQuerySet of this tag's *indirect* supertags,
        i.e. supertags of this tag's direct supertags, but excluding the
        direct supertags themselves.
        """
        direct_supertags = self.get_direct_supertags()
        all_supertags = self.get_all_supertags()
        return all_supertags.difference(direct_supertags)

    def creates_mutually_exclusive_supertags_with_subtag(self, tag):
        """
        Return True if this tag and the given tag (instance, id or name) have
        mutually exclusive supertags, or if this tag directly excludes one of
        the given tag's supertags, or if the given tag directly excludes one of
        this tag's supertags, otherwise False.
        """
        tag_instance = Tag.objects.get_tag_from_argument(tag)
        combined_tags = self.get_all_supertags().union(
            tag_instance.get_all_supertags()
        ).union(
            Tag.objects.filter(id__in={self.id, tag.id})
        )

src/django_taggsonomy/templates/taggsonomy/active_tags.html
{% load taggsonomy %}

<div class="taggsonomy-tags">
  {% for tag in tagset.all %}
    {% tag tag removable_from=tagset url=url %}
  {% endfor %}
</div>

src/django_taggsonomy/templates/taggsonomy/add_tags.html
<form action="{% url 'taggsonomy:add-tags' tagset.id %}" method="POST">
  {% csrf_token %}
  <input type="text" name="tag_names" placeholder="Tag names to add..."
         list="{{ tagset.id }}:tags" autocomplete="off"/>
  <datalist id="{{ tagset.id }}:tags">
    {% for tag in tags %}
    <option value="{{ tag }}">
    {% endfor %}
  </datalist>
  <input type="submit"/>
</form>

src/django_taggsonomy/templates/taggsonomy/tag.html
<span class="taggsonomy-tag" style="background-color: #{{ tag.color }}">
  {% if url%}
    <a href="{{ url }}">{{ tag.name }}</a>
  {% else %}
    {{ tag.name }}
  {% endif %}
  {% if removal_url %}
    <a class="taggsonomy-x"
       href={{ removal_url }}>
      &#x2717
    </a>
  {% endif %}
</span>

src/django_taggsonomy/templates/taggsonomy/tag_confirm_delete.html
{% extends "base.html" %}

{% load taggsonomy %}

{% block content %}
  <h2>
    Deleting tag:
    <span class="taggsonomy-tag" style="background-color: #{{ tag.color }}">
      {{ tag }}
    </span>
  </h2>
  <p>Do you really want to delete this tag?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>
  <a class="button" href="{% url 'taggsonomy:tag-list' %}">Cancel</a>
{% endblock %}

src/django_taggsonomy/templates/taggsonomy/tag_create_form.html
{% extends "base.html" %}

{% load taggsonomy %}

{% block content %}
  <h2>Creating new tag</h2>
  <form class="taggsonomy" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="taggsonomy-form-field">
      {{ form.name.errors }}
      {{ form.name.label_tag }}
      {{ form.name }}
    </div>
    <div class="taggsonomy-form-field">
      {{ form.color.errors }}
      {{ form.color.label_tag }}
      {{ form.color }}
    </div>
    <input class="taggsonomy-action" type="submit"/>
  </form>
  <a href="{% url 'taggsonomy:tag-list' %}">Manage tags</a>
{% endblock %}

src/django_taggsonomy/templates/taggsonomy/tag_edit_form.html
{% extends "base.html" %}

{% load taggsonomy %}

{% block content %}
  <h2>Tag:
    <span class="taggsonomy-tag" style="background-color: #{{ tag.color }}">
      {{ tag }}
    </span>
  </h2>
  <form class="taggsonomy" method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="taggsonomy-form-field">
      {{ form.name.errors }}
      {{ form.name.label_tag }}
      {{ form.name }}
    </div>
    <div class="taggsonomy-form-field">
      {{ form.color.errors }}
      {{ form.color.label_tag }}
      {{ form.color }}
    </div>
    <fieldset class="taggsonomy-form-fieldset">
      <legend>Exclusions</legend>
      <div>
        <h4>Excluded Tags</h4>
        {% for excluded_tag in tag.get_excluded_tags %}
          {% url 'taggsonomy:edit-tag' excluded_tag.id as excluded_tag_edit_url %}
          {% tag excluded_tag removable_from=tag.exclusions url=excluded_tag_edit_url %}
        {% empty %}
          <em>This tag does not exclude any other tags.</em>
        {% endfor %}
      </div>
      <div class="taggsonomy-form-field">
        {{ form.exclusions.errors }}
        {{ form.exclusions.label_tag }}
        {{ form.exclusions }}
      </div>
    </fieldset>
    <fieldset class="taggsonomy-form-fieldset">
      <legend>Supertags</legend>
      <div>
        <h4>Indirect Supertags</h4>
        {% for supertag in tag.get_indirect_supertags %}
          {% url 'taggsonomy:edit-tag' supertag.id as indirect_supertag_edit_url %}
          {% tag supertag url=indirect_supertag_edit_url %}
        {% empty %}
          <em>This tag has no indirect supertags.</em>
        {% endfor %}
      </div>
      <div>
        <h4>Direct Supertags</h4>
        {% for supertag in tag.get_direct_supertags %}
          {% url 'taggsonomy:edit-tag' supertag.id as direct_supertag_edit_url %}
          {% tag supertag removable_from=tag.supertags url=direct_supertag_edit_url %}
        {% empty %}
          <em>This tag has no direct supertags (it is not included by any other tag).</em>
        {% endfor %}
      </div>
      <div class="taggsonomy-form-field">
        {{ form.supertags.errors }}
        {{ form.supertags.label_tag }}
        {{ form.supertags }}
      </div>
    </fieldset>
    <fieldset class="taggsonomy-form-fieldset">
      <legend>Subtags</legend>
      <div>
        <h4>Direct Subtags</h4>
        {% for subtag in tag.get_direct_subtags %}
          {% url 'taggsonomy:edit-tag' subtag.id as direct_subtag_edit_url %}
          {% tag subtag removable_from=tag.subtags url=direct_subtag_edit_url %}
        {% empty %}
          <em>This tag has no direct subtags (it does not include any other tags).</em>
        {% endfor %}
      </div>
      <div class="taggsonomy-form-field">
        {{ form.subtags.errors }}
        {{ form.subtags.label_tag }}
        {{ form.subtags }}
      </div>
      <div>
        <h4>Indirect Subtags</h4>
        {% for subtag in tag.get_indirect_subtags %}
          {% url 'taggsonomy:edit-tag' subtag.id as indirect_subtag_edit_url %}
          {% tag subtag url=indirect_subtag_edit_url %}
        {% empty %}
          <em>This tag has no indirect subtags.</em>
        {% endfor %}
      </div>
    </fieldset>
    <input class="taggsonomy-action" type="submit"/>
  </form>
  <a href="{% url 'taggsonomy:tag-list' %}">Manage tags</a>
{% endblock %}

src/django_taggsonomy/templates/taggsonomy/tag_list.html
{% extends "base.html" %}

{% load taggsonomy %}

{% block content %}
  <h2>Tags</h2>
  {% for tag in object_list %}
  <div class="taggsonomy-container">
    {% url 'taggsonomy:edit-tag' tag.id as tag_edit_url %}
    {% tag tag url=tag_edit_url %}
    <a class="taggsonomy-action" href="{% url 'taggsonomy:delete-tag' tag.id %}">
      Delete
    </a>
  </div>
  {% endfor %}
  <div class="taggsonomy-actions">
    <a class="taggsonomy-action" href="{% url 'taggsonomy:create-tag' %}">
      Create
    </a> new tag
  </div>
{% endblock %}

src/django_taggsonomy/templates/taggsonomy/tag_manager.html
{% load taggsonomy %}
<div class="taggsonomy-container">
  <div class="taggsonomy-heading">Tags</div>
  {% add_tags_form object %}
  {% active_tags object url=url %}
  <div class="taggsonomy-actions">
    <a class="taggsonomy-link" href="{% url 'taggsonomy:tag-list' %}">
      Manage tags
    </a>
  </div>
</div>

src/django_taggsonomy/templates/taggsonomy/tags.html
{% load taggsonomy %}

<div class="taggsonomy-tags">
  {% for tag in tags %}
    {% tag tag url=url %}
  {% endfor %}
</div>